version: "2"

services:
  rabbitmq:
    image: rabbitmq:3.6.10-management
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=50%
    mem_limit: 512m
    restart: unless-stopped
  node-producer:
    image: node:8.9.3
    volumes:
      - ../..:/app/src
      - nodecache:/root/.npm
      - nodemodules:/app/src/node_modules
    working_dir: /app/src
    command: 
      - "yarn" 
      - "nodemon"
      - "-L" 
      - "--delay" 
      - "2" 
      - "-w" 
      - "compile.log" 
      - "build/microservices/node-producer/producer.js"
    restart: unless-stopped
    links: 
      - rabbitmq
  node-consumer:
    image: node:8.9.3
    volumes:
      - ../..:/app/src
      - nodecache:/root/.npm
      - nodemodules:/app/src/node_modules      
    working_dir: /app/src
    command: 
      - "yarn" 
      - "nodemon"
      - "-L" 
      - "--delay" 
      - "2" 
      - "-w" 
      - "compile.log" 
      - "build/microservices/node-consumer/consumer.js"
    restart: unless-stopped
    links: 
      - rabbitmq    
  php-consumer:
    image: dockerlamp/php-composer:0.3
    build:
      context: "../php-composer"
    volumes:
      - ../..:/var/www/html
    working_dir: /var/www/html
    command: [ "php", "-f", "./microservices/php-consumer/consumer.php" ]
    mem_limit: 256m
    restart: unless-stopped
    links:
      - rabbitmq
volumes:
  rabbitdata:
  nodemodules:
  nodecache: