version: "2"

services:
  rabbitmq:
    image: rabbitmq:3.6.10-management
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=50%
    mem_limit: 512m
    restart: unless-stopped
  node-producer:
    image: node:8.9.3
    volumes:
      - ../..:/app/src
      - ../../package.json:/app/package.json
      # - ../../package-lock.json:/app/package-lock.json
      - nodecache:/root/.npm
      - nodemodules:/app/node_modules
    working_dir: /app
    command: "node node_modules/nodemon/bin/nodemon.js -L -w src/microservices src/microservices/node-producer/producer.js"
    # command: ["node", "microservices/producer"]
    restart: unless-stopped
    links: 
      - rabbitmq
  node-consumer:
    image: node:8.9.3
    volumes:
      - ../..:/app/src
      - ../../package.json:/app/package.json
      # - ../../package-lock.json:/app/package-lock.json      
      - nodecache:/root/.npm
      - nodemodules:/app/node_modules      
    working_dir: /app
    command: "node node_modules/nodemon/bin/nodemon.js -L -w src/microservices src/microservices/node-consumer/consumer.js"
    # command: ["node", "microservices/consumer"]    
    restart: unless-stopped
    links: 
      - rabbitmq    
  php-consumer:
    image: dockerlamp/php-composer:0.2
    build:
      context: "../php-composer"
    volumes:
      - ../..:/var/www/html
    working_dir: /var/www/html
    command: [ "php", "-f", "./microservices/php-consumer/consumer.php" ]
    mem_limit: 256m
    restart: unless-stopped
    links:
      - rabbitmq    
volumes:
  rabbitdata:
  nodemodules:
  nodecache: